
version: '3.8'  

services:
  chatbot-ui-shadcn:
    platform: linux/amd64  
    image: amarisg/counselling-chatbot-shadcn-frontend:latest 
    build:
      context: .
      dockerfile: Dockerfile.frontendv2
      platforms: 
        - linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped  
  fastapi-backend:
    platform: linux/amd64  
    image: amarisg/counselling-chatbot-fastapi-backend:latest  
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms:
        - linux/amd64
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped  

networks:
  app-network:
    driver: bridge